apiVersion: 1

datasources:
  - name: InfluxDB_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: defense_org
      defaultBucket: telemetry_stream
    secureJsonData:
      token: telemetry-secret-token-2026
    isDefault: true
